WUC-6: Storybook
Digitable-team/web-ui-components pull request #17
Opened 2022-03-07 13:16 UTC by Uzhastin-Nikita

Installed storybook

![image](https://user-images.githubusercontent.com/71666299/158364260-61241400-245d-46dc-ac66-346a0234dace.png)

2022-03-07 21:58 UTC, Zimtir requested changes

2022-03-07 21:58 UTC, Zimtir commented on package.json
> +  "name": "web-ui-components",
`@digitable-team/web-ui-components`

2022-03-07 21:58 UTC, Zimtir commented on package.json
> +  "license": "ISC",
be sure to discuss with @Adroneleh

2022-03-07 21:58 UTC, Zimtir commented on digitable-storybook/package.json
> +  "name": "digitable-storybook",
`@digitable-team/web-ui-components-storybook`

2022-03-09 11:51 UTC, Zimtir requested changes

2022-03-09 11:51 UTC, Zimtir commented on README.md
> +# web-ui-components
let's rename to repo name

2022-03-09 11:51 UTC, Zimtir commented on README.md
> +`npm run storybook`
```suggestion

```shell
cd digitable-storybook

npm start
  
npm run storybook
```
```

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/.storybook/main.js
> +}
let's add the empty line at eof

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/.storybook/preview.js
> +}
let's add the empty line at eof

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/README.md
> +# Getting Started with Create React App
Create GitHub Pages for Storybook

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/package.json
> +  "private": true,
false

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
Let's change logo file to actual from our web portal

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/public/manifest.json
> +  "name": "Create React App Sample",
Let's actualize with latest info of project instead default

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/src/App.css
> +}
Could you migrate this one to scss?

2022-03-09 11:51 UTC, Zimtir commented on digitable-storybook/src/App.js
> +import './App.css';
Could you add the empty line above?

2022-03-10 23:20 UTC, Uzhastin-Nikita commented on digitable-storybook/README.md
> +# Getting Started with Create React App
Created separate issue

2022-03-10 23:20 UTC, Uzhastin-Nikita commented on digitable-storybook/public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
need help

2022-03-12 21:36 UTC, Zimtir commented on package.json
> +  "license": "ISC",
@Adroneleh please take a look and resolve

2022-03-14 18:45 UTC, Zimtir commented
@Uzhastin-Nikita rebase please

2022-03-15 08:55 UTC, Adroneleh commented
@Uzhastin-Nikita , why commits are written in different styles? [link](https://ru.hexlet.io/blog/posts/git-commit-message)

2022-03-15 09:05 UTC, Adroneleh commented
@Uzhastin-Nikita , Could you write a description?

2022-03-15 11:01 UTC, Adroneleh commented on package.json
> +  "license": "ISC",
![license](https://user-images.githubusercontent.com/32175261/158363514-edd5279c-ede1-4b85-9767-91f89c2fb190.png)
@Zimtir , I think we need take GPL license

2022-03-15 15:34 UTC, merged

2022-03-17 19:00 UTC, Zimtir commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/Digitable-team/web-ui-components/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: